"use client";
import {useState,useEffect,useMemo,useCallback,useRef,useId,Children,isValidElement,cloneElement,type ReactNode} from 'react';
import {Compass,LayoutDashboard,Lightbulb,Package,FlaskConical,BookOpen,ArrowUpRight,Plus,Search,Shirt,PawPrint,ShieldCheck,Database,ChevronRight,ArrowRight,SlidersHorizontal,RefreshCw,Download,Upload,Trash2,History,Check,Link as LinkIcon,AlertCircle,FileText,X,Columns3,Copy,Eye,Save,ArrowLeft,CheckCircle2,MoreHorizontal,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {z} from 'zod';
import {flushSync} from 'react-dom';
import {type Kind,type RecordData,type ResearchRecord,labels,stages,blankRecord,payloadOf,economics,moneyText,costLabels,gaps,recordSchema} from '@/lib/domain';
import {demoRecords} from '@/lib/demo';
const navs=[['overview','研究概览',LayoutDashboard],['clue','需求线索',Lightbulb],['product','候选商品',Package],['experiment','验证与复盘',FlaskConical],['wiki','经验 Wiki',BookOpen]] as const;
type View='overview'|Kind|'data'|'trash';
type Editor={data:RecordData;original?:ResearchRecord};
const formatDate=(s:string)=>s?new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const statusClass=(s:string)=>['已核实','可推进','已完成','已验证'].includes(s)?'green':['进行中','测试中','待拿样'].includes(s)?'amber':s==='已放弃'?'red':'gray';
async function api(path:string,options?:RequestInit){const res=await fetch(path,options);let data:any;try{data=await res.json()}catch{throw new Error('服务响应异常，请稍后重试。')}if(!res.ok)throw new Error(data.error||'操作失败，请重试');return data}
function Field({label,children,wide=false,hint}:{label:string;children:ReactNode;wide?:boolean;hint?:string}){const id=useId();return <div className={'field '+(wide?'wide':'')}><span id={id}>{label}</span>{Children.map(children,child=>isValidElement(child)&&[Input,Textarea,NativeSelect].includes(child.type as any)?cloneElement(child as React.ReactElement<any>,{'aria-labelledby':id,'aria-describedby':hint?id+'-hint':undefined}):child)}{hint&&<small id={id+'-hint'}>{hint}</small>}</div>}
function Badge({children,tone='gray'}:{children:ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
function CategoryIcon({category,small=false}:{category:string;small?:boolean}){const Icon=category==='服饰'?Shirt:PawPrint;return <span className={'category-icon '+(category==='宠物'?'pet ':'')+(small?'small':'')}><Icon size={small?18:26}/></span>}
function Empty({title,text,onAdd,button='新建记录'}:{title:string;text:string;onAdd?:()=>void;button?:string}){return <div className="empty-state"><Compass size={34}/><h3>{title}</h3><p>{text}</p>{onAdd&&<Button variant="outline" onClick={onAdd}><Plus/>{button}</Button>}</div>}
export default function Workbench(){
 const [view,setView]=useState<View>('overview'),[category,setCategory]=useState('全部品类'),[query,setQuery]=useState(''),[status,setStatus]=useState('全部状态'),[sort,setSort]=useState('updated'),[demo,setDemo]=useState(false);
 const [records,setRecords]=useState<ResearchRecord[]>([]),[trash,setTrash]=useState<ResearchRecord[]>([]),[audit,setAudit]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[syncTime,setSyncTime]=useState('');
 const [editor,setEditor]=useState<Editor|null>(null),[editorTab,setEditorTab]=useState('info'),[editorError,setEditorError]=useState(''),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[confirmDelete,setConfirmDelete]=useState<ResearchRecord|null>(null);
 const [selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false),[importPreview,setImportPreview]=useState<any>(null),[importError,setImportError]=useState(''),[page,setPage]=useState(1);
 const fileRef=useRef<HTMLInputElement>(null);
 const agentState=useRef<any>(null);
 useEffect(()=>setPage(1),[view,category,query,status,sort,demo]);
 const reload=useCallback(async()=>{setLoading(true);setError('');try{const d=await api('/api/records');setRecords(d.records);setSyncTime(new Date().toISOString())}catch(e:any){setError(e.message)}finally{setLoading(false)}},[]);
 useEffect(()=>{reload()},[reload]);
 useEffect(()=>{const params=new URLSearchParams(location.search);const v=params.get('view');if(v&&['overview','clue','product','experiment','wiki','data','trash'].includes(v))void go(v as View);if(params.get('demo')==='1')setDemo(true)},[]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 const all=demo?demoRecords:records;
 const filtered=useMemo(()=>all.filter(r=>(category==='全部品类'||r.category===category)&&(view==='overview'||view==='data'||view==='trash'||r.kind===view)&&(status==='全部状态'||r.status===status)&&(!query||[r.title,r.body,r.need,r.audience,r.tags.join(' '),r.sourceNote,r.supplier].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh-CN'):sort==='created'?b.createdAt.localeCompare(a.createdAt):b.updatedAt.localeCompare(a.updatedAt)),[all,category,view,status,query,sort]);
 const scoped=all.filter(r=>category==='全部品类'||r.category===category);
 const products=all.filter(r=>r.kind==='product'&&selected.includes(r.id));
 const pageCount=Math.max(1,Math.ceil(filtered.length/25));
 const pageRecords=filtered.slice((Math.min(page,pageCount)-1)*25,Math.min(page,pageCount)*25);
 const heading=navs.find(n=>n[0]===view)?.[1]||(view==='trash'?'回收站':'数据与备份');
 async function go(v:View){setView(v);setQuery('');setStatus('全部状态');setSelected([]);const u=new URL(location.href);u.searchParams.set('view',v);history.replaceState(null,'',u);if(v==='data'||v==='trash')try{const [a,t]=await Promise.all([api('/api/audit'),api('/api/records?trash=1')]);setAudit(a.events);setTrash(t.records)}catch(e:any){setError(e.message)}}
 function openEditor(r:ResearchRecord){setEditor({data:payloadOf(r),original:r});setEditorTab('info');setEditorError('');setDirty(false)}
 function create(kind:Kind,data?:Partial<RecordData>){if(demo){toast.info('当前为只读演示，请先切换到我的工作台。');return}setEditor({data:{...blankRecord(kind,category==='宠物'?'宠物':'服饰'),title:'',...data}});setEditorTab('info');setEditorError('');setDirty(false)}
 function closeEditor(){if(busy)return;if(dirty&&!demo)setDiscard(true);else setEditor(null)}
 function patch(data:Partial<RecordData>){setEditor(e=>e?{...e,data:{...e.data,...data}}:e);setDirty(true);setEditorError('')}
 async function save(e:React.FormEvent){e.preventDefault();if(!editor||busy||demo)return;const valid=recordSchema.safeParse({...editor.data,tags:editor.data.tags.filter(Boolean)});if(!valid.success){setEditorError(valid.error.issues.map(i=>i.message).join('；'));return}setBusy(true);setEditorError('');try{const res=await api('/api/records',{method:editor.original?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editor.original?{id:editor.original.id,version:editor.original.version,data:valid.data}:valid.data)});setRecords(rs=>[res.record,...rs.filter(r=>r.id!==res.record.id)]);setEditor(null);setDirty(false);setSyncTime(new Date().toISOString());toast.success('已保存到你的研究空间')}catch(e:any){setEditorError(e.message)}finally{setBusy(false)}}
 async function move(r:ResearchRecord,action:'delete'|'restore'){if(busy||demo)return;setBusy(true);try{const d=await api('/api/records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id,version:r.version,action})});if(action==='delete'){setRecords(rs=>rs.filter(x=>x.id!==r.id));setTrash(t=>[d.record,...t]);setEditor(null);setDirty(false)}else{setTrash(rs=>rs.filter(x=>x.id!==r.id));setRecords(t=>[d.record,...t])}setSelected(s=>s.filter(x=>x!==r.id));setConfirmDelete(null);toast.success(action==='delete'?'已移入回收站，可随时恢复':'已恢复记录')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 function transition(r:ResearchRecord){if(demo)return;setEditor(null);if(r.kind==='clue')create('product',{category:r.category,title:r.title,audience:r.audience,scenario:r.scenario,need:r.need||r.body,relatedIds:[r.id],tags:r.tags,nextAction:'补充候选方案、供应商信息与成本'});if(r.kind==='product')create('experiment',{category:r.category,title:r.title+'：样品验证',relatedIds:[r.id],hypothesis:r.need,nextAction:'明确测试方法与通过标准'});if(r.kind==='experiment')create('wiki',{category:r.category,title:r.title+'：复盘',relatedIds:[r.id,...r.relatedIds],body:`研究问题\n${r.hypothesis||'待补充'}\n\n验证方法\n${r.method||'待补充'}\n\n实际结果\n${r.result||'尚未完成验证'}\n\n判断与适用边界\n${r.decision||'待补充，不作为已验证结论'}`,tags:r.tags})}
 async function download(format:'json'|'csv'){try{const res=await fetch('/api/export?format='+format);if(!res.ok){const e=await res.json() as {error:string};throw new Error(e.error)}const blob=await res.blob();downloadBlob(blob,`选品工作台-${new Date().toISOString().slice(0,10)}.${format}`);toast.success('已导出有效记录；回收站和操作日志不包含在备份中')}catch(e:any){toast.error(e.message)}}
 function downloadBlob(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 async function prepareImport(f?:File){if(!f)return;setImportError('');try{if(f.size>20_000_000)throw new Error('文件不能超过 20 MB');const data=JSON.parse(await f.text());if(data.schemaVersion!==1||!Array.isArray(data.records)||!data.records.length||data.records.length>5000)throw new Error('请选择本工具导出的 JSON 文件，单次 1–5000 条记录。');if(new Set(data.records.map((r:any)=>r?.id)).size!==data.records.length)throw new Error('文件包含重复编号');for(const r of data.records){if(!r||!z.string().uuid().safeParse(r.id).success||!recordSchema.safeParse(payloadOf(r)).success)throw new Error('文件内有无效记录，请核对字段、来源和状态。')}setImportPreview(data)}catch(e:any){setImportError(e.message)}finally{if(fileRef.current)fileRef.current.value=''}}
 async function doImport(){setBusy(true);setImportError('');let imported=0,skipped=0;try{const chunks:any[][]=[];let chunk:any[]=[];let size=0;for(const r of importPreview.records){const bytes=JSON.stringify(r).length;if(bytes>900000)throw new Error('单条记录过大，无法导入');if(chunk.length>=100||size+bytes>900000){chunks.push(chunk);chunk=[];size=0}chunk.push(r);size+=bytes}if(chunk.length)chunks.push(chunk);for(const batch of chunks){const d=await api('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({schemaVersion:1,records:batch})});imported+=d.imported;skipped+=d.skipped}setImportPreview(null);toast.success(`导入 ${imported} 条，跳过 ${skipped} 条已有记录`);await reload()}catch(e:any){setImportError(`已导入 ${imported} 条。${e.message}。可重试，已成功的记录不会重复导入。`);await reload()}finally{setBusy(false)}}

 function pick(id:string,on:boolean){if(on&&selected.length>=4){toast.info('一次最多比较 4 个商品');return}setSelected(s=>on?[...s,id]:s.filter(x=>x!==id))}
 const titleDescriptions:Record<View,string>={overview:'把需求变成线索，把判断留给证据。',clue:'保存原始反馈，分清事实、推测和待验证的问题。',product:'对比解决方案、供货信息和真实成本。',experiment:'先写通过标准，再记录实际结果。',wiki:'让验证过的经验，成为下一次研究的起点。',data:'备份你的研究，查看每一次修改。',trash:'误删的记录可以在这里恢复。'};
 agentState.current={all,demo,create,dirty,busy};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[
 {name:'search_research_records',title:'查询选品研究',description:'读取当前空间的研究记录，返回标题、状态与缺失信息。不会修改记录。',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['服饰','宠物']}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){const args=z.object({query:z.string().max(200).optional(),category:z.enum(['服饰','宠物']).optional()}).strict().parse(input);return agentState.current.all.filter((r:ResearchRecord)=>(!args.category||r.category===args.category)&&(!args.query||[r.title,r.body,r.need].join(' ').includes(args.query))).slice(0,50).map((r:ResearchRecord)=>({id:r.id,title:r.title,kind:r.kind,status:r.status,missing:gaps(r)}))}},
 {name:'start_research_record',title:'准备研究记录',description:'打开新建记录表单，不会保存。用户可以检查并保存。',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['clue','product','experiment','wiki']},category:{type:'string',enum:['服饰','宠物']},title:{type:'string'}},required:['kind','category','title'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const args=z.object({kind:z.enum(['clue','product','experiment','wiki']),category:z.enum(['服饰','宠物']),title:z.string().trim().min(1).max(150)}).strict().parse(input);if(agentState.current.demo)throw new Error('请先退出只读示例空间');if(agentState.current.dirty||agentState.current.busy)throw new Error('请先处理当前未保存的内容');flushSync(()=>agentState.current.create(args.kind,{title:args.title,category:args.category}));return {status:'form_opened',saved:false,title:args.title}}}
 ];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(e=>console.warn('Browser tool registration unavailable',e))}catch(e){console.warn('Browser tool registration unavailable',e)}}return()=>life.abort()},[]);
 const renderTable=(list:ResearchRecord[],compact=false)=><Table><TableHeader><TableRow>{!compact&&view==='product'&&<TableHead className="check-cell">对比</TableHead>}<TableHead>研究主题</TableHead><TableHead>状态</TableHead>{!compact&&<TableHead>{view==='product'?'单笔贡献利润':'证据性质'}</TableHead>}<TableHead>下一步</TableHead><TableHead className="date-cell">更新</TableHead></TableRow></TableHeader><TableBody>{list.map(r=><TableRow key={r.id}>{!compact&&view==='product'&&<TableCell className="check-cell"><Checkbox aria-label={'对比 '+r.title} checked={selected.includes(r.id)} onCheckedChange={v=>pick(r.id,v===true)}/></TableCell>}<TableCell><button className="record-link" onClick={()=>openEditor(r)}><CategoryIcon category={r.category} small/><span><strong>{r.title}</strong><small>{r.category} · {compact?labels[r.kind]:r.tags.join(' / ')||'未添加标签'}</small></span></button></TableCell><TableCell><Badge tone={statusClass(r.status)}>{r.status}</Badge></TableCell>{!compact&&<TableCell>{view==='product'?<span className={(economics(r.costs).profit??0)<0?'negative':'number'}>{moneyText(economics(r.costs).profit)}</span>:<Badge tone={r.evidence==='事实'?'green':'gray'}>{r.evidence}</Badge>}</TableCell>}<TableCell><span className="next-step">{r.nextAction||'待安排'}</span></TableCell><TableCell className="date-cell">{formatDate(r.updatedAt)}</TableCell></TableRow>)}</TableBody></Table>;
 return <><Toaster position="top-center" richColors/><div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Compass/></span><div>选品研习社<small>SELECTION STUDIO</small></div></div><div className="workspace"><span className="avatar">研</span><div>{demo?'示例研究空间':'我的研究空间'}<small>服饰 · 宠物</small></div><ShieldCheck size={16}/></div><div className="nav-label">工作台</div><nav>{navs.map(([id,label,Icon])=><button key={id} onClick={()=>go(id)} className={view===id?'nav-item active':'nav-item'}><Icon size={19}/>{label}{view===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span>从一个好问题开始</span><p>记录证据，验证假设。<br/>让经验成为下一次的起点。</p></div><button className={'nav-item '+(view==='data'?'active':'')} onClick={()=>go('data')}><Database size={18}/>数据与备份</button><button className={'nav-item '+(view==='trash'?'active':'')} onClick={()=>go('trash')}><Trash2 size={18}/>回收站{trash.length>0&&<span className="nav-count">{trash.length}</span>}</button><div className="private-note"><ShieldCheck size={14}/>私有访问 · 按账号隔离</div></div></aside><div className="main-shell"><header className="topbar"><div>工作台 <ChevronRight size={14}/> {heading}</div><div className="top-actions"><button className="text-button" onClick={()=>{setDemo(!demo);setSelected([]);setQuery('');setStatus('全部状态')}}><Eye size={15}/>{demo?'返回我的工作台':'查看示例'}</button><button className="mobile-data text-button" onClick={()=>go('data')}><Database size={16}/>数据</button><button className="sync" onClick={reload} disabled={loading} title="刷新数据"><i className={error?'error-dot':''}/>{loading?'正在同步':error?'连接异常':demo?'只读演示':syncTime?'已同步':'尚未同步'}<RefreshCw size={13}/></button></div></header><main className="main-content"><div className="page-heading"><div><div className="eyebrow">{demo?'示例数据 · 不代表市场事实':'你的下一个好商品，从这里开始'}</div><h1>{heading}</h1><p>{titleDescriptions[view]}</p></div>{!['data','trash'].includes(view)&&<Button onClick={()=>create(view==='overview'?'clue':view as Kind)} disabled={demo}><Plus/>{view==='overview'||view==='clue'?'记录新线索':'新建'+labels[view as Kind]}</Button>}</div>
 {demo&&<div className="demo-banner"><Eye size={18}/><span>这是虚构的只读演示。价格、需求和结果不构成选品建议。</span><button onClick={()=>{setDemo(false);setSelected([])}}>进入我的工作台 <ArrowRight size={15}/></button></div>}
 {error&&!demo&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}</span><Button size="sm" variant="outline" onClick={reload}>重试</Button></div>}
 {!['data','trash'].includes(view)&&<div className="filterbar"><div className="segmented">{['全部品类','服饰','宠物'].map(c=><button key={c} onClick={()=>{setCategory(c);setSelected([])}} className={category===c?'selected':''}>{c==='服饰'?<Shirt size={15}/>:c==='宠物'?<PawPrint size={15}/>:null}{c}</button>)}</div><div className="filters-right"><div className="search-box"><Search size={16}/><Input aria-label="搜索研究记录" placeholder="搜索标题、需求、标签…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{view!=='overview'&&<NativeSelect aria-label="按状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option>全部状态</option>{stages[view as Kind].map(s=><option key={s}>{s}</option>)}</NativeSelect>}<NativeSelect aria-label="排序方式" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">最近更新</option><option value="created">最近创建</option><option value="title">标题排序</option></NativeSelect></div></div>}
 {view==='overview'&&<><div className="metrics">{(['clue','product','experiment','wiki'] as Kind[]).map((k,i)=><button className="metric" key={k} onClick={()=>go(k)}><span>{['需求线索','候选商品','进行中验证','已验证经验'][i]}<ArrowUpRight size={16}/></span><strong>{scoped.filter(r=>r.kind===k&&(k==='experiment'?r.status==='进行中':k==='wiki'?r.status==='已验证':true)).length}</strong><small>{['从真实场景出发','比较不同解决方案','让每个假设可检验','积累可复用的判断'][i]}</small></button>)}</div>{all.length===0&&!query?<section className="welcome-panel"><div><span className="eyebrow">开始你的第一轮研究</span><h2>先找到需求，再寻找商品。</h2><p>从一次穿着体验，或一个养宠难题开始。<br/>记录原始线索，再逐步补充候选商品和验证结果。</p><div className="button-row"><Button variant="outline" onClick={()=>create('clue')}>建立第一条线索 <ArrowUpRight/></Button><button className="text-button" onClick={()=>setDemo(true)}>先看完整示例</button></div></div><div className="category-art"><div><Shirt size={46}/><span>服饰研究</span></div><div><PawPrint size={46}/><span>宠物研究</span></div></div></section>:<div className="pipeline-strip">{(['clue','product','experiment','wiki'] as Kind[]).map((k,i)=><button key={k} onClick={()=>go(k)}><span>0{i+1}</span><strong>{labels[k]}</strong><b>{scoped.filter(r=>r.kind===k).length}</b>{i<3&&<ChevronRight size={17}/>}</button>)}</div>}<div className="content-grid"><section className="panel"><div className="section-title"><h2>最近的研究</h2><span>{filtered.length} 条记录</span></div>{filtered.length?renderTable(filtered.slice(0,8),true):<Empty title={query?'没有匹配的记录':'你的研究，从一条线索开始'} text={query?'试试其他关键词，或切换品类。':'保存一个问题、客户反馈或商品链接，逐步形成判断。'} onAdd={query?undefined:()=>create('clue')} button="记录需求线索"/>}</section><aside className="panel guide-panel"><div className="section-title"><h2>{scoped.length?'下一步行动':'一轮完整的研究'}</h2><Compass size={19}/></div>{scoped.length?scoped.filter(r=>r.nextAction&&!['已完成','已验证','已放弃'].includes(r.status)).slice(0,4).map(r=><button className="action-item" key={r.id} onClick={()=>openEditor(r)}><span className="action-dot"/><div><strong>{r.nextAction}</strong><small>{r.title}</small>{r.dueDate&&<small className={r.dueDate<new Date().toLocaleDateString('sv-SE')?'negative':''}>{r.dueDate} 到期</small>}</div><ChevronRight size={14}/></button>):['记录有来源的需求','比较候选商品与成本','设计一个小范围验证','把结果整理成经验'].map((s,i)=><div className="guide-step" key={s}><b>0{i+1}</b><span>{s}</span></div>)}<p className="subtle">信息不全时，保留“待验证”。</p></aside></div></>}
 {(['clue','product','experiment','wiki'] as string[]).includes(view)&&<>{view==='product'&&selected.length>0&&<div className="compare-bar"><span>已选择 {selected.length} / 4 个商品</span><Button size="sm" disabled={selected.length<2} onClick={()=>setCompare(true)}><Columns3/>比较商品</Button><button className="text-button" onClick={()=>setSelected([])}>取消选择</button></div>}{view==='wiki'?<div className="wiki-grid">{pageRecords.map(r=><button className="wiki-card" key={r.id} onClick={()=>openEditor(r)}><div><BookOpen size={22}/><Badge tone={statusClass(r.status)}>{r.status}</Badge></div><h2>{r.title}</h2><p>{r.body||'尚未填写正文'}</p><footer>{r.category}<span>{r.relatedIds.length} 条关联 · {formatDate(r.updatedAt)}</span></footer></button>)}</div>:view==='experiment'?<div className="kanban">{stages.experiment.map(s=><section key={s} className="kanban-column"><h2><span className={'status-dot '+statusClass(s)}/>{s}<b>{filtered.filter(r=>r.status===s).length}</b></h2>{filtered.filter(r=>r.status===s).map(r=><button className="experiment-card" key={r.id} onClick={()=>openEditor(r)}><Badge>{r.category}</Badge><h3>{r.title}</h3><p>{r.hypothesis||'待填写验证假设'}</p><div><FlaskConical size={14}/>{r.metric||'待设置指标'}</div><footer>{r.dueDate||'未设置到期日'}<ArrowUpRight size={15}/></footer></button>)}{!filtered.some(r=>r.status===s)&&<div className="kanban-empty">暂无记录</div>}</section>)}</div>:<section className="panel"><div className="section-title"><h2>{heading}</h2><span>{filtered.length} 条 · {view==='product'?'勾选 2–4 项进行比较':'点击标题查看详情'}</span></div>{filtered.length?renderTable(pageRecords):<Empty title={loading&&!demo?'正在加载研究记录…':'还没有匹配的'+labels[view as Kind]} text="调整筛选条件，或记录你的第一个研究主题。" onAdd={()=>create(view as Kind)}/>}</section>}{!filtered.length&&['wiki','experiment'].includes(view)&&<Empty title={'开始建立你的'+labels[view as Kind]} text={view==='wiki'?'记录适用范围、结论和依据，关联到原始研究。':'明确一个假设，写下验证方法与通过标准。'} onAdd={()=>create(view as Kind)}/>}</>}
 {view==='data'&&<><div className="data-grid"><section className="panel data-card"><Download/><h2>导出研究数据</h2><p>JSON 保留全部有效记录及关联；CSV 适合在表格中分析。回收站与日志不包含在导出文件中。</p><div className="button-row"><Button disabled={demo||loading} onClick={()=>download('json')}>完整 JSON 备份</Button><Button variant="outline" disabled={demo||loading} onClick={()=>download('csv')}>导出 CSV</Button></div></section><section className="panel data-card"><Upload/><h2>导入备份</h2><p>支持本工具导出的 JSON，每次最多 5000 条、20 MB，分批保存。仅追加不存在的记录，已有记录不会被覆盖。中断后可重试。</p><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={e=>prepareImport(e.target.files?.[0])}/><Button variant="outline" disabled={demo} onClick={()=>fileRef.current?.click()}>选择 JSON 文件</Button>{importError&&<p className="negative" role="alert">{importError}</p>}</section></div><div className="data-note"><ShieldCheck size={18}/><div><strong>你的研究，有迹可循</strong><p>记录按登录账号隔离，修改采用版本校验。删除进入回收站；多窗口冲突会提示刷新，保留当前输入。</p></div><Button variant="outline" onClick={()=>go('trash')}>查看回收站</Button></div><section className="panel"><div className="section-title"><h2><History size={18}/>最近操作</h2><span>最近 200 次</span></div>{audit.length?<Table><TableHeader><TableRow><TableHead>操作</TableHead><TableHead>记录</TableHead><TableHead>时间</TableHead></TableRow></TableHeader><TableBody>{audit.map(a=><TableRow key={a.id}><TableCell><Badge>{a.action}</Badge></TableCell><TableCell>{a.title}</TableCell><TableCell>{formatDate(a.created_at)}</TableCell></TableRow>)}</TableBody></Table>:<Empty title="还没有操作记录" text="创建、编辑、导入与恢复记录后，操作会显示在这里。"/>}</section></>}
 {view==='trash'&&<section className="panel"><div className="section-title"><h2>可恢复的记录</h2><span>{trash.length} 条</span></div>{trash.length?<Table><TableHeader><TableRow><TableHead>标题</TableHead><TableHead>类型</TableHead><TableHead>删除时间</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{trash.map(r=><TableRow key={r.id}><TableCell>{r.title}</TableCell><TableCell>{labels[r.kind]}</TableCell><TableCell>{formatDate(r.deletedAt||'')}</TableCell><TableCell><Button size="sm" variant="outline" disabled={busy||demo} onClick={()=>move(r,'restore')}>恢复</Button></TableCell></TableRow>)}</TableBody></Table>:<Empty title="回收站是空的" text="移入回收站的记录可以恢复，研究不会因为一次误删而丢失。"/>}</section>}
 {['clue','product','wiki'].includes(view)&&pageCount>1&&<div className="pagination"><span>共 {filtered.length} 条 · 第 {Math.min(page,pageCount)} / {pageCount} 页</span><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>上一页</Button><Button variant="outline" size="sm" disabled={page>=pageCount} onClick={()=>setPage(p=>p+1)}>下一页</Button></div>}
 <footer className="page-footer"><span>选品研习社</span><span>有来源的判断，才值得复用。</span></footer></main></div></div>
 <Dialog open={!!editor} onOpenChange={o=>{if(!o)closeEditor()}}><DialogContent className="editor-dialog" onInteractOutside={e=>{if(busy)e.preventDefault()}}><DialogHeader><DialogTitle>{editor?.original?'研究详情':'新建'+(editor?labels[editor.data.kind]:'记录')}</DialogTitle><DialogDescription>{demo?'虚构示例，只读浏览。切换回我的工作台后可以创建真实记录。':'来源、假设和结果分别记录。未确认的成本请留空。'}</DialogDescription></DialogHeader>{editor&&<form onSubmit={save} className="editor-form"><fieldset disabled={busy||demo} className="editor-fieldset"><div className="editor-title-row"><CategoryIcon category={editor.data.category}/><Input autoFocus aria-label="记录标题" placeholder="给这次研究起一个清楚的名字" value={editor.data.title} maxLength={150} onChange={e=>patch({title:e.target.value})}/></div></fieldset><div className="editor-tabs" role="tablist" aria-label="研究详情分区">{[['info',editor.data.kind==='wiki'?'正文与结论':'基本信息'],['evidence','证据与关联'],...(editor.data.kind==='product'?[['cost','成本测算']]:[]),['actions','行动与判断']].map(([id,name])=><button key={id} type="button" role="tab" aria-selected={editorTab===id} onClick={()=>setEditorTab(id)}>{name}</button>)}</div><div className="editor-scroll"><fieldset disabled={busy||demo} className="form-grid">
 {editorTab==='info'&&<><Field label="研究品类"><NativeSelect value={editor.data.category} onChange={e=>patch({category:e.target.value as '服饰'|'宠物'})}><option>服饰</option><option>宠物</option></NativeSelect></Field><Field label="当前状态"><NativeSelect value={editor.data.status} onChange={e=>patch({status:e.target.value})}>{stages[editor.data.kind].map(s=><option key={s}>{s}</option>)}</NativeSelect></Field><Field label="标签（用逗号分隔）"><Input value={editor.data.tags.join(',')} placeholder="例如：通勤, 尺码适配" onChange={e=>patch({tags:e.target.value.split(/[,，]/).map(s=>s.trim())})}/></Field><Field label="记录负责人"><Input value={editor.data.ownerName} placeholder="你的姓名或内部负责人" onChange={e=>patch({ownerName:e.target.value})}/></Field>
 {['clue','product'].includes(editor.data.kind)&&<><Field label={editor.data.category==='服饰'?'目标客户 / 体型':'宠物种类 / 体型 / 主人群体'}><Input value={editor.data.audience} onChange={e=>patch({audience:e.target.value})} placeholder={editor.data.category==='服饰'?'例如：日常通勤人群':'例如：经常带中型犬外出的主人'}/></Field><Field label="使用场景"><Input value={editor.data.scenario} onChange={e=>patch({scenario:e.target.value})} placeholder="在什么情况下遇到问题？"/></Field><Field label="需求与购买理由" wide><Textarea value={editor.data.need} onChange={e=>patch({need:e.target.value})} placeholder="遇到什么问题？为什么现有方案还不够好？" rows={3}/></Field></>}
 {editor.data.kind==='product'&&<><Field label="竞品与替代方案" wide><Textarea value={editor.data.competitor} onChange={e=>patch({competitor:e.target.value})} placeholder="竞品名称、链接、价格及差异。注明采集日期。"/></Field><Field label="供应商与供货信息" wide><Textarea value={editor.data.supplier} onChange={e=>patch({supplier:e.target.value})} placeholder="供应商、报价日期、起订量、交期、报价有效期"/></Field><Field label={editor.data.category==='服饰'?'面料、尺码、剪裁与工艺':'材质、规格、结构与清洁方式'} wide><Textarea value={editor.data.attributes} onChange={e=>patch({attributes:e.target.value})} placeholder="记录商品属性、样品编号与需要核实的项目"/></Field></>}
 {editor.data.kind==='experiment'&&<><Field label="待验证假设" wide><Textarea value={editor.data.hypothesis} onChange={e=>patch({hypothesis:e.target.value})} placeholder="希望通过这次测试回答哪个问题？"/></Field><Field label="验证方法与样本条件" wide><Textarea value={editor.data.method} onChange={e=>patch({method:e.target.value})} placeholder="样品、参与者、步骤、环境、测试周期"/></Field><Field label="观察指标"><Input value={editor.data.metric} onChange={e=>patch({metric:e.target.value})} placeholder="例如：洗后尺寸变化"/></Field><Field label="事先约定的通过标准"><Input value={editor.data.target} onChange={e=>patch({target:e.target.value})} placeholder="填写数值、条件或可核验标准"/></Field><Field label="实际结果" wide><Textarea value={editor.data.result} onChange={e=>patch({result:e.target.value})} placeholder="写实际观察到的结果、样本量和异常。完成验证时必填。" rows={4}/></Field></>}
 <Field label={editor.data.kind==='wiki'?'经验正文（纯文本）':'补充说明 / 原始反馈'} wide hint={editor.data.kind==='wiki'?'建议写清：问题、方法、结果、结论、适用范围和例外。系统按文本保存，链接请放在来源字段。':undefined}><Textarea value={editor.data.body} onChange={e=>patch({body:e.target.value})} rows={editor.data.kind==='wiki'?13:3} placeholder={editor.data.kind==='wiki'?'把验证过的经验写下来，保留适用边界。':'粘贴原始内容，保留上下文，避免只记录自己的解释。'}/></Field></>}
 {editorTab==='evidence'&&<><Field label="证据性质"><NativeSelect value={editor.data.evidence} onChange={e=>patch({evidence:e.target.value as RecordData['evidence']})}><option>待验证</option><option>事实</option><option>推测</option></NativeSelect></Field><Field label="采集日期"><Input type="date" value={editor.data.collectedAt} onChange={e=>patch({collectedAt:e.target.value})}/></Field><Field label="原始来源链接" wide><Input type="url" value={editor.data.sourceUrl} onChange={e=>patch({sourceUrl:e.target.value})} placeholder="https://…"/>{editor.data.sourceUrl&&/^https?:\/\//.test(editor.data.sourceUrl)&&<a className="inline-link" href={editor.data.sourceUrl} target="_blank" rel="noopener noreferrer">打开原始来源 <ArrowUpRight size={13}/></a>}</Field><Field label="来源说明" wide><Textarea value={editor.data.sourceNote} onChange={e=>patch({sourceNote:e.target.value})} placeholder="例如：访谈日期与匿名编号、供应商报价单编号、样品测试记录。无网址时请填写可追溯说明。"/></Field><div className="field wide"><span>关联研究记录</span><div className="relation-picker">{all.filter(r=>r.id!==editor.original?.id).map(r=><label key={r.id}><Checkbox checked={editor.data.relatedIds.includes(r.id)} onCheckedChange={v=>patch({relatedIds:v?[...editor.data.relatedIds,r.id]:editor.data.relatedIds.filter(x=>x!==r.id)})}/><span>{r.title}<small>{labels[r.kind]} · {r.category}</small></span></label>)}{all.filter(r=>r.id!==editor.original?.id).length===0&&<p>创建其他记录后，可在此建立关联。</p>}{editor.data.relatedIds.filter(id=>!all.some(r=>r.id===id)).map(id=><label key={id}><Checkbox checked onCheckedChange={()=>patch({relatedIds:editor.data.relatedIds.filter(x=>x!==id)})}/><span>已删除或不可用的关联<small>取消勾选可移除此关联</small></span></label>)}</div><small>关联线索、商品、验证记录与经验，让判断可以追溯。</small></div></>}
 {editorTab==='cost'&&<><div className="cost-intro wide">单位：人民币 / 单。已确认没有该项费用时填 0；未知请留空。售价使用折扣后的实际收入。</div>{Object.entries(costLabels).map(([k,label])=><Field key={k} label={label}><Input type="number" min="0" max={k==='feePercent'?100:10000000} step="0.01" value={editor.data.costs[k as keyof RecordData['costs']]??''} placeholder="待确认" onChange={e=>patch({costs:{...editor.data.costs,[k]:e.target.value===''?null:Number(e.target.value)}})}/></Field>)}</>}
 {editorTab==='actions'&&<><Field label="下一步动作" wide><Input value={editor.data.nextAction} onChange={e=>patch({nextAction:e.target.value})} placeholder="一个明确、可执行的动作"/></Field><Field label="到期日期"><Input type="date" value={editor.data.dueDate} onChange={e=>patch({dueDate:e.target.value})}/></Field><Field label="当前状态"><NativeSelect value={editor.data.status} onChange={e=>patch({status:e.target.value})}>{stages[editor.data.kind].map(s=><option key={s}>{s}</option>)}</NativeSelect></Field><Field label="判断依据与适用边界" wide><Textarea value={editor.data.decision} onChange={e=>patch({decision:e.target.value})} rows={6} placeholder="为什么继续、调整或放弃？哪些数据支持结论？哪些情况尚未验证？"/></Field></>}
 </fieldset>
 {editorTab==='cost'&&<div className="cost-results">{economics(editor.data.costs).complete?<><div><span>单笔贡献利润</span><strong className={(economics(editor.data.costs).profit??0)<0?'negative':''}>{moneyText(economics(editor.data.costs).profit)}</strong><small>贡献率 {economics(editor.data.costs).margin===null?'—':economics(editor.data.costs).margin!.toFixed(1)+'%'}</small></div><div><span>盈亏平衡获客成本</span><strong>{moneyText(economics(editor.data.costs).breakEven)}</strong><small>不含固定成本与税费；不是净利润</small></div><p>单笔贡献 = 到手售价 − 采购 − 包装 − 物流 − 平台费用 − 获客 − 售后。平台费用按到手售价 × 费率估算；复杂计费请另行核对。</p></>:<div className="cost-incomplete"><AlertCircle size={21}/><strong>成本尚未补齐，不计算利润</strong><p>待确认：{economics(editor.data.costs).missing.map(k=>costLabels[k]).join('、')}</p></div>}</div>}
 {editorTab==='actions'&&<div className="research-gaps"><h3><Lightbulb size={17}/>记录完整性检查</h3>{gaps(editor.data).length?<ul>{gaps(editor.data).map(g=><li key={g}>{g}</li>)}</ul>:<p><CheckCircle2 size={16}/>关键记录项已补齐，仍需自行判断证据质量。</p>}<small>根据已填写字段检查，不代表市场验证或 AI 预测。</small></div>}
 {editor.original&&<div className="record-meta">创建于 {formatDate(editor.original.createdAt)} · 更新于 {formatDate(editor.original.updatedAt)} · 版本 {editor.original.version}</div>}
 </div>{editorError&&<div className="form-error" role="alert"><AlertCircle size={16}/>{editorError}</div>}<div className="editor-footer"><div>{editor.original&&!demo&&<><Button type="button" variant="ghost" size="sm" aria-label="移入回收站" disabled={busy} onClick={()=>setConfirmDelete(editor.original!)}><Trash2/></Button>{editor.data.kind!=='wiki'&&<Button type="button" variant="outline" size="sm" disabled={busy||dirty} onClick={()=>transition(editor.original!)}>{editor.data.kind==='clue'?'建立候选商品':editor.data.kind==='product'?'建立验证任务':'整理为 Wiki'}<ArrowRight size={14}/></Button>}</>}</div><div className="button-row"><Button type="button" variant="outline" disabled={busy} onClick={closeEditor}>{demo?'关闭':'取消'}</Button>{!demo&&<Button type="submit" disabled={busy}><Save size={16}/>{busy?'正在保存…':'保存记录'}</Button>}</div></div></form>}</DialogContent></Dialog>
 <Dialog open={discard} onOpenChange={setDiscard}><DialogContent><DialogHeader><DialogTitle>保留未保存的内容？</DialogTitle><DialogDescription>关闭后，这次尚未保存的修改会丢失。</DialogDescription></DialogHeader><div className="button-row right"><Button variant="outline" onClick={()=>{setDiscard(false);setEditor(null);setDirty(false)}}>放弃修改</Button><Button onClick={()=>setDiscard(false)}>继续编辑</Button></div></DialogContent></Dialog>
 <Dialog open={!!confirmDelete} onOpenChange={o=>{if(!o)setConfirmDelete(null)}}><DialogContent><DialogHeader><DialogTitle>移入回收站</DialogTitle><DialogDescription>“{confirmDelete?.title}”将从当前列表移除，可在回收站恢复。关联记录会保留引用。</DialogDescription></DialogHeader><div className="button-row right"><Button variant="outline" disabled={busy} onClick={()=>setConfirmDelete(null)}>取消</Button><Button variant="destructive" disabled={busy} onClick={()=>confirmDelete&&move(confirmDelete,'delete')}>移入回收站</Button></div></DialogContent></Dialog>
 <Dialog open={compare} onOpenChange={setCompare}><DialogContent className="compare-dialog"><DialogHeader><DialogTitle>候选商品对比</DialogTitle><DialogDescription>未知成本显示待确认。不同需求的商品应结合各自验证目标判断。</DialogDescription></DialogHeader><div className="compare-scroll"><Table><TableHeader><TableRow><TableHead>比较维度</TableHead>{products.map(r=><TableHead key={r.id}>{r.title}</TableHead>)}</TableRow></TableHeader><TableBody>{[['品类',(r:ResearchRecord)=>r.category],['当前状态',(r:ResearchRecord)=>r.status],['目标客户',(r:ResearchRecord)=>r.audience||'待确认'],['需求与购买理由',(r:ResearchRecord)=>r.need||'待确认'],['供应商',(r:ResearchRecord)=>r.supplier||'待确认'],['到手售价',(r:ResearchRecord)=>moneyText(r.costs.price)],['单笔贡献利润',(r:ResearchRecord)=>moneyText(economics(r.costs).profit)],['盈亏平衡获客成本',(r:ResearchRecord)=>moneyText(economics(r.costs).breakEven)],['证据性质',(r:ResearchRecord)=>r.evidence],['尚缺信息',(r:ResearchRecord)=>gaps(r).join('；')||'关键字段已补齐'],['下一步',(r:ResearchRecord)=>r.nextAction||'待安排']].map(([name,fn])=><TableRow key={name as string}><TableCell>{name as string}</TableCell>{products.map(r=><TableCell key={r.id}>{(fn as (r:ResearchRecord)=>string)(r)}</TableCell>)}</TableRow>)}</TableBody></Table></div><p className="subtle">贡献利润尚未扣除固定成本及税费。</p></DialogContent></Dialog>
 <Dialog open={!!importPreview} onOpenChange={o=>{if(!o&&!busy){setImportPreview(null);setImportError('')}}}><DialogContent><DialogHeader><DialogTitle>导入预览</DialogTitle><DialogDescription>共 {importPreview?.records?.length||0} 条记录。相同编号的记录将跳过，不覆盖已有内容。</DialogDescription></DialogHeader><div className="import-list">{importPreview?.records?.slice(0,5).map((r:any,i:number)=><p key={i}>{r.category} · {r.title}</p>)}{importPreview?.records?.length>5&&<small>其余记录将在导入后显示。</small>}</div>{importError&&<p role="alert" className="negative">{importError}</p>}<div className="button-row right"><Button variant="outline" disabled={busy} onClick={()=>setImportPreview(null)}>取消</Button><Button disabled={busy} onClick={doImport}>{busy?'正在导入…':'确认导入'}</Button></div></DialogContent></Dialog>
 </>;
}
